const ADD_MESSAGE = "ADD_MESSAGE";
const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
const ADD_USER = "ADD_USER";
const USERS_LIST = "USERS_LIST";

export { ADD_MESSAGE, MESSAGE_RECEIVED, ADD_USER, USERS_LIST };
